/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#09090a",
        secondary: {
          100: "#cdf8f4",
          200: "#9af0e8",
          300: "#68e9dd",
          400: "#35e1d1",
          500: "#03dac6",
          600: "#03c4b2",
          700: "#026d63",
          800: "#01413b",
          900: "#012c28",
        },
        primary: {
          900: "#341d5c",
          800: "#3e236e",
          700: "#522e92",
          600: "#5d34a5",
          500: "#673ab7",
          400: "#7e57c2",
          300: "#9575cd",
          200: "#b39ddb",
        },
        backgroundCard: {
          bug: "#8BD674",
          dark: "#6F6E78",
          electric: "#fdd835",
          dragon: "#7383B9",
          fairy: "#EC8FE6",
          fighting: "#FB91A3",
          fire: "#F3634E",
          flying: "#7ACFF7",
          ghost: "#8571BE",
          grass: "#4caf50",
          ground: "#ffab91",
          ice: "#6DF6E5",
          normal: "#B5B9C4",
          poison: "#B567CE",
          psychic: "#FA7179",
          rock: "#bcaaa4",
          steel: "#88a0b5",
          water: "#4AA5F7",
        },
        // boxType: {
        //   bug: "#8CB230",
        //   dark: "#58575F",
        //   dragon: "#0F6AC0",
        //   electric: "#f9a825",
        //   fairy: "#ED6EC7",
        //   fighting: "#FD4363",
        //   fire: "#d32f2f",
        //   flying: "#29b6f6",
        //   ghost: "#556AAE",
        //   grass: "#357a38",
        //   ground: "#DD7748",
        //   ice: "#26c6da",
        //   normal: "#9DA0AA",
        //   poison: "#A552CC",
        //   psychic: "#e91e63",
        //   rock: "#6d4c41",
        //   steel: "#416688",
        //   water: "#0288d1",
        // },
        boxType: {
          bug: {
            light: "#e7f5e8",
            mediumLight: "#d2ebd4",
            default: "#8BD674",
            mediumDark: "#82c66a",
            dark: "#7dbf66",
          },
          dark: {
            light: "#e6e6e7",
            mediumLight: "#c4c4c6",
            default: "#6F6E78",
            mediumDark: "#64646d",
            dark: "#62626b",
          },
          dragon: {
            light: "#e6e9f2",
            mediumLight: "#b4bcd8",
            default: "#7383B9",
            mediumDark: "#6976a7",
            dark: "#6773a7",
          },
          electric: {
            light: "#fffae8",
            mediumLight: "#ffe9a4",
            default: "#fdd835",
            mediumDark: "#e5c02f",
            dark: "#e4c32e",
          },
          fairy: {
            light: "#fceaf7",
            mediumLight: "#f3c2e8",
            default: "#EC8FE6",
            mediumDark: "#d27ec9",
            dark: "#d27dc9",
          },
          fighting: {
            light: "#ffe8ed",
            mediumLight: "#ffb3c2",
            default: "#FB91A3",
            mediumDark: "#e0808e",
            dark: "#e17f8f",
          },
          fire: {
            light: "#fde3df",
            mediumLight: "#f6b3a8",
            default: "#F3634E",
            mediumDark: "#d75845",
            dark: "#d65545",
          },
          flying: {
            light: "#e8f7fd",
            mediumLight: "#c3e6fb",
            default: "#7ACFF7",
            mediumDark: "#6fc3e2",
            dark: "#6eb6d9",
          },
          ghost: {
            light: "#e8e6f4",
            mediumLight: "#c5c1e7",
            default: "#8571BE",
            mediumDark: "#7967a8",
            dark: "#7764a8",
          },
          grass: {
            light: "#e5f3e8",
            mediumLight: "#c7e3c6",
            default: "#4caf50",
            mediumDark: "#469d49",
            dark: "#449949",
          },
          ground: {
            light: "#fff2ee",
            mediumLight: "#ffc7ba",
            default: "#ffab91",
            mediumDark: "#e69e80",
            dark: "#e69b80",
          },
          ice: {
            light: "#f0fbfb",
            mediumLight: "#c7f3f3",
            default: "#6DF6E5",
            mediumDark: "#63dbc9",
            dark: "#63dac8",
          },
          normal: {
            light: "#f3f4f6",
            mediumLight: "#d9dadf",
            default: "#B5B9C4",
            mediumDark: "#a6a9b0",
            dark: "#a3a7b0",
          },
          poison: {
            light: "#f4e7f4",
            mediumLight: "#dbb3e1",
            default: "#B97FC9",
            mediumDark: "#a977b2",
            dark: "#a16fae",
          },
          psychic: {
            light: "#ffe9ea",
            mediumLight: "#f8b5b8",
            default: "#FA7179",
            mediumDark: "#dd636a",
            dark: "#dc6268",
          },
          rock: {
            light: "#f3eeec",
            mediumLight: "#d8c7c3",
            default: "#bcaaa4",
            mediumDark: "#a3948f",
            dark: "#a5938e",
          },
          steel: {
            light: "#f1f5f7",
            mediumLight: "#d0e0e8",
            default: "#88a0b5",
            mediumDark: "#7b8fa1",
            dark: "#7990a1",
          },
          water: {
            light: "#e5f1fd",
            mediumLight: "#b0d7fa",
            default: "#4AA5F7",
            mediumDark: "#4393d8",
            dark: "#4394da",
          },
        },
        sucess: "#34D399",
        alert: "#F87171",
      },
      fontFamily: {
        regular: "Inter_400Regular",
        semibold: "Inter_600SemiBold",
        bold: "Inter_700Bold",
        extrabold: "Inter_800ExtraBold",
      },
      backgroundImage: {
        alola: "url('./src/assets/regions/alola.png')",
      },
    },
  },
  plugins: [],
};
