export const types = [
  "bug",
  "dark",
  "dragon",
  "electric",
  "fairy",
  "fighting",
  "fire",
  "flying",
  "ghost",
  "grass",
  "ground",
  "ice",
  "normal",
  "poison",
  "psychic",
  "rock",
  "steel",
  "water",
];

export const typesObjColors: { [chave: string]: string } = {
  bug: "#8BD674",
  dark: "#6F6E78",
  electric: "#fdd835",
  dragon: "#7383B9",
  fairy: "#EC8FE6",
  fighting: "#FB91A3",
  fire: "#F3634E",
  flying: "#7ACFF7",
  ghost: "#8571BE",
  grass: "#4caf50",
  ground: "#ffab91",
  ice: "#6DF6E5",
  normal: "#B5B9C4",
  poison: "#B567CE",
  psychic: "#FA7179",
  rock: "#bcaaa4",
  steel: "#88a0b5",
  water: "#4AA5F7",
};
